// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace nTierDemoX {
	
	
	public partial class AgregarEmpleado {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtApellido;
		
		protected System.Web.UI.WebControls.TextBox txtNombre;
		
		protected System.Web.UI.WebControls.TextBox txtPuesto;
		
		protected System.Web.UI.WebControls.TextBox txtDireccion;
		
		protected System.Web.UI.WebControls.TextBox txtCiudad;
		
		protected System.Web.UI.WebControls.TextBox txtRegion;
		
		protected System.Web.UI.WebControls.TextBox txtCodigoPostal;
		
		protected System.Web.UI.WebControls.TextBox txtPais;
		
		protected System.Web.UI.WebControls.TextBox txtExtension;
		
		protected System.Web.UI.WebControls.Button btnYES;
		
		protected System.Web.UI.WebControls.Button btnNO;
	}
}
