// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace nTierDemoX {
	
	
	public partial class BorrarEmpleado {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblEmpleadoID;
		
		protected System.Web.UI.WebControls.Label lblApellido;
		
		protected System.Web.UI.WebControls.Label lblNombre;
		
		protected System.Web.UI.WebControls.Label lblPuesto;
		
		protected System.Web.UI.WebControls.Label lblDireccion;
		
		protected System.Web.UI.WebControls.Label lblCiudad;
		
		protected System.Web.UI.WebControls.Label lblRegion;
		
		protected System.Web.UI.WebControls.Label lblCodigoPostal;
		
		protected System.Web.UI.WebControls.Label lblPais;
		
		protected System.Web.UI.WebControls.Label lblExtension;
		
		protected System.Web.UI.WebControls.Button btnYES;
		
		protected System.Web.UI.WebControls.Button btnNO;
	}
}
